version: '3.7'

services:

  nginx1:
    build:
      context: .
      target: nginx1
    ports:
      - "8000:80"
    depends_on:
      - php1

  php1:
    build:
      context: .
      target: php1
    depends_on:
      - db
      - minio

  nginx2:
    build:
      context: .
      target: nginx2
    ports:
      - "8001:80"
    depends_on:
      - php2

  php2:
    build:
      context: .
      target: php2
    depends_on:
      - db
      - minio

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
#    volumes:
#     - ./docker-compose/mysql:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db

  migrate:
    build:
      context: .
      target: php_base
    depends_on:
      - db
    command: php artisan migrate:fresh --seed

  minio:
    image: quay.io/minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ROOTNAME
      MINIO_ROOT_PASSWORD: PASSWORD123
    command: server /data --console-address ":9001"

  maildev:
    image: maildev/maildev
    restart: always
    ports:
      - 8081:1080
    environment:
      - TZ=Asia/Shanghai
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
