# Version de la syntaxe Docker Compose
version: '3.8'

services:
  # Service Nginx 1
  nginx1:
    image: nginx:alpine  
    ports:
      - "8081:80"  
    volumes:
      - ./nginx1/default.conf:/etc/nginx/conf.d/default.conf  
      - ./site:/var/www  
  
    depends_on:
      - php1  

  # Service Nginx 2
  nginx2:
    image: nginx:alpine
    container_name: nginx2
    ports:
      - "8082:80"
    volumes:
      - C:/Users/pierr/Documents/3i-ESGI/Projet Semes/docker-project/nginx2/default.conf:/etc/nginx/conf.d/default.conf
      - ./site:/var/www
    depends_on:
      - php2

  # Service PHP 1
  php1:
    build:
      context: ./php1  
    container_name: php1
    volumes:
      - ./site:/var/www  
    depends_on:
      - mysql 

  # Service PHP 2
  php2:
    build:
      context: ./php2
    container_name: php2
    volumes:
      - ./site:/var/www
    depends_on:
      - mysql

  # Service MySQL
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: laravel  
      MYSQL_USER: root  
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD: 
    volumes:
      - db_data:/var/lib/mysql  

volumes:
  db_data:
